-- Pending phone verification sessions (replaces in-memory Map).
-- Safe for load-balanced servers: any instance can validate and consume sessions.
-- Run once: psql -f addPendingPhoneVerificationsTable.sql (or run in your DB client)

CREATE TABLE IF NOT EXISTS public.pending_phone_verifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(255) NOT NULL,
    phone character varying(20) NOT NULL,
    password_hash character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    used_at timestamp with time zone
);

CREATE INDEX IF NOT EXISTS idx_pending_phone_verifications_lookup
    ON public.pending_phone_verifications (email, phone)
    WHERE used_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_pending_phone_verifications_expires_at
    ON public.pending_phone_verifications (expires_at);

COMMENT ON TABLE public.pending_phone_verifications IS 'Short-lived sessions between Create Password and phone verification; used instead of in-memory store for load balancing';
